=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/runningexample.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->

<xs:element name="name" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
<xs:element name="country" type="xs:string"/>
<xs:element name="profession" type="xs:string"/>
<!-- <xs:element name="creator" type="xs:string"/> -->
<xs:element name="birthyear" type="xs:positiveInteger"/>
<xs:element name="firstmentioning" type="xs:positiveInteger"/>
<xs:element name="deathyear" type="xs:positiveInteger"/>
<xs:element name="creationyear" type="xs:string"/>


<!-- definition of complex elements -->

<xs:complexType name="creator">
	<xs:attribute name="id" type="xs:string"/>
</xs:complexType>

<xs:complexType name="artwork">
	 <xs:sequence>
    	<xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
    	<xs:element name="creator" minOccurs="0" maxOccurs="unbounded">
    		<xs:complexType>
				<xs:attribute name="ref" type="xs:string"/>
			</xs:complexType>
    	</xs:element>
   		<xs:element ref="creationyear" minOccurs="0" maxOccurs="unbounded"/>	 			      
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/>
</xs:complexType>

<xs:element name="data">
<xs:complexType>
	<xs:sequence>
	    <xs:choice maxOccurs="unbounded">
			<xs:element name="painting" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:complexContent>
					<xs:extension base="artwork">
					
					</xs:extension>
				</xs:complexContent>			
			</xs:complexType>
			 <xs:key name="painting">
	          <xs:selector xpath="painting"/>
	          <xs:field xpath="@id"/>
          </xs:key>
			</xs:element>
	      <xs:element name="building" minOccurs="0" maxOccurs="unbounded">
		  <xs:complexType>
		  <xs:complexContent>
		  	<xs:extension base="artwork">
			    <xs:sequence>  
			      <xs:element ref="city" minOccurs="0" maxOccurs="unbounded"/>
			      <xs:element ref="country" minOccurs="0" maxOccurs="unbounded"/>
			      <xs:element name="part" minOccurs="0" maxOccurs="unbounded">
				  <xs:complexType>
				    <xs:sequence>
				      <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
				      <xs:element name="room" minOccurs="0" maxOccurs="unbounded">
						  <xs:complexType>
						    <xs:sequence>
						    	 <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
						    </xs:sequence>
						  </xs:complexType>
						</xs:element>     
				    </xs:sequence>				   
				  </xs:complexType>
				</xs:element>
			    </xs:sequence>
		     </xs:extension>
		    </xs:complexContent>
		  </xs:complexType>
		  <xs:key name="building">
	          <xs:selector xpath="building"/>
	          <xs:field xpath="@id"/>
          </xs:key>
		</xs:element>
	      <xs:element name="artist" minOccurs="0" maxOccurs="unbounded">
		  <xs:complexType>
		    <xs:sequence>
		      <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
		      <xs:element ref="profession" minOccurs="0" maxOccurs="unbounded"/>
		      <xs:element ref="birthyear" minOccurs="0" maxOccurs="unbounded"/>
		      <xs:element ref="deathyear" minOccurs="0" maxOccurs="unbounded"/>      
		    </xs:sequence>
		    <xs:attribute name="id" type="xs:string"/>
		  </xs:complexType>
		  <xs:key name="artist">
	          <xs:selector xpath="artist"/>
	          <xs:field xpath="@id"/>
          </xs:key>
		</xs:element>
	    </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:keyref name="creator" refer="artist">
	  <xs:selector xpath="creator"/>
	  <xs:field xpath="@ref"/>
  </xs:keyref>
</xs:element>
</xs:schema>

=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/runningexample.xml
<?xml version="1.0" encoding="UTF-8"?>

<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="runningexample.xsd">

	<painting>
		<name>Mona Lisa</name>
		<creator ref="1"/>
		<creationyear>around 1503/1507</creationyear>
	</painting>
	
	<painting>
		<name>Das Rosenkranzfest</name>
		<creator ref="2"/>
		<creationyear>1758</creationyear>
	</painting>
	
	<building>
		<name>Empire State Building</name>
		<city>New York City</city>
		<country>USA</country>
		<part>
			<name>1st Floor</name>
			<room>
			<name>entrance hall</name>
			</room>
		</part>	
	</building>	
	
	<building>
		<name>Chrysler Building</name>
		<city>New York City</city>
		<country>Unknown</country>		
	</building>
	
	<artist id="1">
		<name>Leonardo da Vinci</name>
		<occupation>painter</occupation>
		<birthyear>1452</birthyear>
		<deathyear>1519</deathyear>
	</artist>
	
	<artist id="2">
		<name>Jakob Jenewein</name>
		<occupation>painter</occupation>
	</artist>
	
	<artist>
		<deathyear>1950</deathyear>
	</artist>	

</data>

=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/runningexample4.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="runningexample.xsd">
	<painting id="1">
		<name>Mona Lisa</name>
		<creator ref="5"/>
	</painting>	
	<painting id="2">
		<name>The Last Supper</name>
		<creator ref="5"/>
	</painting>	
	<building id="3">
		<name>Empire State Building</name>
		<creator ref="6"/>
		<city>New York City</city>
		<country>USA</country>		
	</building>		
	<building id="4">
		<name>Chrysler Building</name>
		<creator ref="7"/>
		<city>New York City</city>
		<country>unknown</country>		
	</building>	
	<artist id="5">
		<name>Leonardo da Vinci</name>
		<profession>architect</profession>
	</artist>		
	<artist id="6">
		<name>William F. Lamb</name>
		<profession>architect</profession>
	</artist>	
</data>

=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/runningexample3.xml
<?xml version="1.0" encoding="UTF-8"?>

<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="runningexample.xsd">

	<painting>
		<name>Mona Lisa</name>
		<creator ref="1"/>
		<creationyear>around 1503-1507</creationyear>
	</painting>
	
	<painting>
		<name>The Last Supper</name>
		<creator ref="1"/>
		<creationyear>1494-1497</creationyear>
	</painting>
	
	<building>
		<name>Empire State Building</name>
		<creator ref="2"/>
		<city>New York City</city>
		<country>USA</country>		
	</building>	
	
	<building>
		<name>Chrysler Building</name>
		<creator ref="3"/>
		<city>New York City</city>
		<country>Unknown</country>		
	</building>
	
	<artist id="1">
		<name>Leonardo da Vinci</name>
		<occupation>architect</occupation>
	</artist>	
	
	<artist id="2">
		<name>William F. Lamb</name>
		<occupation>architect</occupation>
	</artist>		

</data>

=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/runningexample2.xml
<?xml version="1.0" encoding="UTF-8"?>

<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="runningexample.xsd">

	<painting>
		<name>Mona Lisa</name>
		<creator ref="1"/>
		<creationyear>around 1503/1507</creationyear>
	</painting>
	
	<building>
		<name>Empire State Building</name>
		<creator ref="3"/>
		<city>New York City</city>
		<country>USA</country>
		<part>
			<name>1st Floor</name>
			<room>
			<name>entrance hall</name>
			</room>
		</part>	
	</building>	
	
	<building>
		<name>Chrysler Building</name>
		<city>New York City</city>
		<country>Unknown</country>		
	</building>
	
	<artist id="1">
		<name>Leonardo da Vinci</name>
		<occupation>architect</occupation>
		<birthyear>1452</birthyear>
		<deathyear>1519</deathyear>
	</artist>
	
	<artist id="2">
		<name>Vincent van Gogh</name>
		<occupation>painter</occupation>
		<birthyear>1853</birthyear>
		<deathyear>1890</deathyear>
	</artist>
	

</data>
