=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/testschema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="lString" type="xs:string"/>
<xs:element name="lDouble" type="xs:double"/>
<xs:element name="lInt" type="xs:integer"/>
<xs:element name="lBool" type="xs:boolean"/>
<xs:element name="lDate" type="xs:date"/>
<xs:element name="lTime" type="xs:time"/>
<xs:element name="lDateTime" type="xs:dateTime"/>

<xs:element name="root">
<xs:complexType>
	<xs:sequence>
	    <xs:choice maxOccurs="unbounded">
	    	<xs:element name="child1" minOccurs="0" maxOccurs="unbounded">
			  <xs:complexType>
			    <xs:sequence>
			    	<xs:element name="child2" minOccurs="0" maxOccurs="unbounded">
					  <xs:complexType>
					    <xs:sequence>
					    	<xs:element name="child3" minOccurs="0" maxOccurs="unbounded">
							  <xs:complexType>
							    <xs:sequence>
							    	<xs:element name="child4" minOccurs="0" maxOccurs="unbounded">
									  <xs:complexType>
									    <xs:sequence>
									    	<xs:element name="leaf" minOccurs="0" maxOccurs="unbounded"/>	
									    	<xs:element name="lString" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="lDouble" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="lInt" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="lBool" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="lDate" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="lTime" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element name="lDateTime" minOccurs="0" maxOccurs="unbounded"/>										  
									    </xs:sequence>
									    <xs:attribute name="aString" type="xs:string"/>
									    <xs:attribute name="aDouble" type="xs:double"/>
									    <xs:attribute name="aInt" type="xs:integer"/>
									    <xs:attribute name="aBool" type="xs:boolean"/>
									    <xs:attribute name="aDate" type="xs:date"/>
									    <xs:attribute name="aTime" type="xs:time"/>
									    <xs:attribute name="aDateTime" type="xs:dateTime"/>
									    <xs:attribute name="aString2" type="xs:string"/>
									    <xs:attribute name="aDouble2" type="xs:double"/>
									    <xs:attribute name="aInt2" type="xs:integer"/>
									    <xs:attribute name="aBool2" type="xs:boolean"/>
									    <xs:attribute name="aDate2" type="xs:date"/>
									    <xs:attribute name="aTime2" type="xs:time"/>
									    <xs:attribute name="aDateTime2" type="xs:dateTime"/>
									  </xs:complexType>
									</xs:element>
							    </xs:sequence>
							    <xs:attribute name="aString" type="xs:string"/>
							    <xs:attribute name="aDouble" type="xs:double"/>
							    <xs:attribute name="aInt" type="xs:integer"/>
							    <xs:attribute name="aBool" type="xs:boolean"/>
							    <xs:attribute name="aDate" type="xs:date"/>
							    <xs:attribute name="aTime" type="xs:time"/>
							    <xs:attribute name="aDateTime" type="xs:dateTime"/>
							    <xs:attribute name="aString2" type="xs:string"/>
							    <xs:attribute name="aDouble2" type="xs:double"/>
							    <xs:attribute name="aInt2" type="xs:integer"/>
							    <xs:attribute name="aBool2" type="xs:boolean"/>
							    <xs:attribute name="aDate2" type="xs:date"/>
							    <xs:attribute name="aTime2" type="xs:time"/>
							    <xs:attribute name="aDateTime2" type="xs:dateTime"/>
							  </xs:complexType>
							</xs:element>
					    </xs:sequence>
					    <xs:attribute name="aString" type="xs:string"/>
					    <xs:attribute name="aDouble" type="xs:double"/>
					    <xs:attribute name="aInt" type="xs:integer"/>
					    <xs:attribute name="aBool" type="xs:boolean"/>
					    <xs:attribute name="aDate" type="xs:date"/>
					    <xs:attribute name="aTime" type="xs:time"/>
					    <xs:attribute name="aDateTime" type="xs:dateTime"/>
					    <xs:attribute name="aString2" type="xs:string"/>
					    <xs:attribute name="aDouble2" type="xs:double"/>
					    <xs:attribute name="aInt2" type="xs:integer"/>
					    <xs:attribute name="aBool2" type="xs:boolean"/>
					    <xs:attribute name="aDate2" type="xs:date"/>
					    <xs:attribute name="aTime2" type="xs:time"/>
					    <xs:attribute name="aDateTime2" type="xs:dateTime"/>
					  </xs:complexType>
					</xs:element>
			    </xs:sequence>
			    <xs:attribute name="aString" type="xs:string"/>
			    <xs:attribute name="aDouble" type="xs:double"/>
			    <xs:attribute name="aInt" type="xs:integer"/>
			    <xs:attribute name="aBool" type="xs:boolean"/>
			    <xs:attribute name="aDate" type="xs:date"/>
			    <xs:attribute name="aTime" type="xs:time"/>
			    <xs:attribute name="aDateTime" type="xs:dateTime"/>
			    <xs:attribute name="aString2" type="xs:string"/>
			    <xs:attribute name="aDouble2" type="xs:double"/>
			    <xs:attribute name="aInt2" type="xs:integer"/>
			    <xs:attribute name="aBool2" type="xs:boolean"/>
			    <xs:attribute name="aDate2" type="xs:date"/>
			    <xs:attribute name="aTime2" type="xs:time"/>
			    <xs:attribute name="aDateTime2" type="xs:dateTime"/>
			  </xs:complexType>
			</xs:element>
		</xs:choice>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/testdata/testdata.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="testschema.xsd">
	<child1>
		<child2 aString="a">
			<child3 aDouble="1.1">
				<child4 aInt="5">
					<lString>lString1</lString>
				</child4>
				<child4 aBool="true">
					<lDouble>2.2</lDouble>
				</child4>
			</child3>
			<child3 aBool="0">
				<child4 aDate="1645-08-27">
					<lInt>3</lInt>
				</child4>
				<child4 aTime="09:30:14">
					<lBool>true()</lBool>
				</child4>
			</child3>
			<child3 aDateTime="1840-02-03T07:13:01">
				<child4>
					<lDate>1950-01-31</lDate>
				</child4>
				<child4>
					<lTime>03:50:55</lTime>
				</child4>
			</child3>
			<child3>
				<child4>
					<lDateTime>1810-05-15T10:41:05</lDateTime>
				</child4>
				<child4>
					<lString>lString8</lString>
				</child4>
			</child3>
		</child2>
		<child2>
			<child3>
				<child4>
					<lString>lString9</lString>
				</child4>
				<child4>
					<lString>lString10</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString11</lString>
				</child4>
				<child4>
					<lString>lString12</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString13</lString>
				</child4>
				<child4>
					<lString>lString14</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString15</lString>
				</child4>
				<child4>
					<lString>lString16</lString>
				</child4>
			</child3>
		</child2>	
	</child1>
	<child1>
		<child2>
			<child3>
				<child4>
					<lString>lString1</lString>
				</child4>
				<child4>
					<lString>lString2</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString3</lString>
				</child4>
				<child4>
					<lString>lString4</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString5</lString>
				</child4>
				<child4>
					<lString>lString6</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString7</lString>
				</child4>
				<child4>
					<lString>lString8</lString>
				</child4>
			</child3>
		</child2>
		<child2>
			<child3>
				<child4>
					<lString>lString1</lString>
				</child4>
				<child4>
					<lString>lString2</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString3</lString>
				</child4>
				<child4>
					<lString>lString4</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString5</lString>
				</child4>
				<child4>
					<lString>lString6</lString>
				</child4>
			</child3>
			<child3>
				<child4>
					<lString>lString7</lString>
				</child4>
				<child4>
					<lString>lString8</lString>
				</child4>
			</child3>
		</child2>	
	</child1>
</root>
