=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/demo.data/demo_database_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:demo="demo" targetNamespace="demo">

	<xs:element name="data">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="building" type="demo:buildingType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="painting" type="demo:paintingType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="architect" type="demo:personType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="artist" type="demo:personType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="buildingType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="creator" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id"/>
	</xs:complexType>

	<xs:complexType name="paintingType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="creator" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="startwork" type="xs:integer"/>
			<xs:element name="endwork" type="xs:integer"/>		
		</xs:sequence>
		<xs:attribute name="id"/>
	</xs:complexType>

	<xs:complexType name="personType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="birthyear" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id"/>
	</xs:complexType>

	<xs:complexType name="adressType">
		<xs:sequence>
			<xs:element name="city" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="country" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== Project-KONDA/pattern-based-quality-analysis/qualitypatternmodel/demo.data/demo_database.xml
<?xml version="1.0" encoding="UTF-8"?>

<demo:data xmlns:demo="demo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="demo https://raw.githubusercontent.com/Project-KONDA/pattern-based-quality-analysis/master/qualitypatternmodel/demo.data/demo_database_schema.xsd">	

	<!--  BUILDINGS -->
	
	<demo:building demo:id="101" demo:recorded="2020-11-01T09:00:00" demo:last-modified-date="2020-11-01" demo:last-modified-time="09:00:00">
		<demo:name >Empire State Building</demo:name>
		<demo:city>New York City</demo:city>
		<demo:country>USA</demo:country>	
		<demo:creator>301</demo:creator>
		<demo:creator demo:last-modified-date="2022-11-01" demo:ref="301"/>
		<demo:address>
			<demo:city>New York City</demo:city>
			<demo:country>USA</demo:country>
		</demo:address>
	</demo:building>	
	
	<demo:building demo:id="102" demo:recorded="2020-11-01T09:00:00" demo:last-modified-date="2020-11-01" demo:last-modified-time="09:00:01">
		<demo:name>Chrysler Building</demo:name>
		<demo:city>New York City</demo:city>
		<demo:country>unknown</demo:country>
		<demo:creator>302</demo:creator>
		<demo:creator demo:ref="302"/>
		<demo:address>
			<demo:city>New York City</demo:city>
			<demo:country>unknown</demo:country>
		</demo:address>
	</demo:building>
	
	<demo:building demo:id="103" demo:recorded="2020-11-01T09:00:00" demo:last-modified-date="2020-11-01" demo:last-modified-time="09:00:00">
		<demo:name>Royal Palace</demo:name>
		<demo:city>unknown</demo:city>
		<demo:country>unknown</demo:country>
		<demo:creator>103</demo:creator>
		<demo:creator demo:ref="103"/>
		<demo:address>
			<demo:city>unknown</demo:city>
			<demo:country>unknown</demo:country>
		</demo:address>
	</demo:building>
	
	<!--  PAINTINGS -->
	
	<demo:painting demo:id="201" demo:recorded="2020-10-01T07:00:00">
		<demo:title>The Starry Night</demo:title>
		<demo:creator>401</demo:creator>
		<demo:endwork>1889</demo:endwork>
	</demo:painting>
	
	<demo:painting demo:id="202" demo:recorded="2020-10-02T08:00:00">
		<demo:title>Wheatfield with Crows</demo:title>
		<demo:creator>9</demo:creator>
		<demo:endwork>1890</demo:endwork>
	</demo:painting>
	
	<demo:painting demo:id="203" demo:recorded="2020-10-03T09:00:00" demo:modified="false" demo:last-modified-date="2020-10-03" demo:last-modified-time="09:00:00">
		<demo:title>The Last Supper</demo:title>
		<demo:creator>402</demo:creator>
		<demo:startwork>1492</demo:startwork>
		<demo:endwork>1498</demo:endwork>
	</demo:painting>
	
	<demo:painting demo:id="204" demo:recorded="2020-10-04T10:00:00" demo:modified="true" demo:last-modified-date="2020-10-04" demo:last-modified-time="10:00:00">
		<demo:title>Mona Lisa</demo:title>
		<demo:title demo:lang="fr">La Gioconda</demo:title>
		<demo:creator>402</demo:creator>
		<demo:startwork>1503</demo:startwork>
		<demo:endwork>1516</demo:endwork>
	</demo:painting>
	
	<demo:painting demo:id="205" demo:recorded="2020-11-01T09:00:00" demo:last-modified-date="2020-11-01" demo:last-modified-time="09:00:00">
		<demo:title>Salvator Mundi</demo:title>
		<demo:creator>402</demo:creator>
		<demo:startwork>1490</demo:startwork>
		<demo:endwork>1500</demo:endwork>
	</demo:painting>
	
	<!--  ARCHITECTS -->
	
	<demo:architect demo:id="301">
		<demo:name>William Frederick Lamb</demo:name>
		<demo:name>William F. Lamb</demo:name>
		<demo:name>Wiliam F. Lamb</demo:name>
		<demo:birthyear>1883</demo:birthyear>
		<demo:birthyear>1884</demo:birthyear>
		<demo:birthyear>2883</demo:birthyear>
		<demo:deathyear>1952</demo:deathyear>		
	</demo:architect>
	
	<demo:architect demo:id="302">
		<demo:name>William Van Alen</demo:name>
		<demo:birthyear>1882</demo:birthyear>
		<demo:deathyear>1954</demo:deathyear>		
	</demo:architect>	
	
	<!--  ARTISTS -->
	
	<demo:artist demo:id="401">
		<demo:name>Vincent van Gogh</demo:name>
		<demo:birthyear>1853</demo:birthyear>
		<demo:deathyear>1890</demo:deathyear>		
	</demo:artist>
	
	<demo:artist demo:id="402">
		<demo:name>Leonardo Da Vinci</demo:name>
		<demo:birthyear>1452</demo:birthyear>
		<demo:birthyear>1453</demo:birthyear>
		<demo:deathyear>1519</demo:deathyear>		
	</demo:artist>
	
</demo:data>
